package harnessobs

import (
	"bufio"
	"io"
	"os"
	"time"
)

func normalizedOpenCodeRawEvents(rawPath string, sessionFacts []Event, now time.Time) ([]Event, error) {
	// File opening stays outside the scanner helper so tests can exercise the
	// byte replay path with in-memory readers while production keeps path errors
	// precise.
	file, err := os.Open(rawPath)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	return scanOpenCodeRawEvents(file, sessionFacts, now)
}

// scanOpenCodeRawEvents prepends session facts, then replays raw provider
// lines through unsafe-input rejection before producing normalized events.
func scanOpenCodeRawEvents(file io.Reader, sessionFacts []Event, now time.Time) ([]Event, error) {
	scanner := bufio.NewScanner(file)
	scanner.Buffer(make([]byte, 0, 64*1024), DefaultMaxLineBytes)
	lineNo := 0

	// Session facts are trusted context generated by setup/collection; raw
	// provider lines are appended only after per-line safety checks pass.
	events := append([]Event{}, sessionFacts...)
	for scanner.Scan() {
		lineNo++
		var err error

		events, err = appendNormalizedRawLine(events, scanner.Bytes(), lineNo, now)
		if err != nil {
			return nil, err
		}
	}

	return events, scanner.Err()
}
